#!/bin/sh

wheel() {
  platform="$1"
  wheel_tag="$2"
  rm -rf build/
  echo "--- $platform ---"
  PYI_WHEEL_TAG="$wheel_tag" PYI_PLATFORM="$platform" python -m build --no-isolation --wheel --outdir=dist . > /dev/null
}

wheel Windows-64bit-intel win_amd64
wheel Linux-64bit-intel manylinux2014_x86_64

rm -rf build/
python -m build --sdist --no-isolation --outdir=dist > /dev/null
